namespace Marketing.DataAccess.Entities;

/// <summary>
/// Root of the persistence model. Supplies identity, multi-tenancy, auditing, soft delete and
/// optimistic concurrency to every table in the schema.
/// <para>
/// None of the audit or tenancy members are ever assigned by application code. They are populated
/// by <c>AuditingSaveChangesInterceptor</c>; assigning them by hand is treated as a defect because
/// it is the only way those columns can disagree with the interceptor's view of the world.
/// </para>
/// </summary>
public abstract class BaseEntity
{
    /// <summary>
    /// Primary key, generated by the database as a <c>bigint</c> identity.
    /// <para>
    /// Zero until the row is inserted. Code that needs to relate two new entities in one unit of
    /// work must therefore assign the <em>navigation property</em> rather than the foreign key, and
    /// let Entity Framework fill the key in after the insert - assigning the key by hand would
    /// write a zero.
    /// </para>
    /// </summary>
    public long Id { get; set; }

    /// <summary>
    /// Owning tenant. Null only for platform-level rows (tenants, global roles, platform admins).
    /// Set by the interceptor from <c>ITenantContext</c>; never accepted from a request.
    /// </summary>
    public long? TenantId { get; set; }

    /// <summary>User who created the row.</summary>
    public long CreatedBy { get; set; }

    /// <summary>Instant the row was created, in UTC.</summary>
    public DateTimeOffset CreatedOn { get; set; }

    /// <summary>User who last modified the row.</summary>
    public long? ModifiedBy { get; set; }

    /// <summary>Instant the row was last modified, in UTC.</summary>
    public DateTimeOffset? ModifiedOn { get; set; }

    /// <summary>User who soft-deleted the row.</summary>
    public long? DeletedBy { get; set; }

    /// <summary>Instant the row was soft-deleted, in UTC.</summary>
    public DateTimeOffset? DeletedOn { get; set; }

    /// <summary>
    /// Soft-delete marker. Deleted rows are excluded by a global query filter, so ordinary queries
    /// never see them and no caller has to remember to filter.
    /// </summary>
    public bool IsDeleted { get; set; }

    /// <summary>
    /// Optimistic concurrency token.
    /// <para>
    /// PostgreSQL has no SQL Server style <c>rowversion</c>. This property is mapped onto the
    /// built-in <c>xmin</c> system column, which holds the id of the transaction that last wrote
    /// the row and therefore changes on every update at zero storage cost.
    /// </para>
    /// </summary>
    public uint RowVersion { get; set; }
}
